import {fileURLToPath} from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync,writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL("../../", import.meta.url));
const db=new PGlite();
await db.exec(`CREATE SCHEMA cron; CREATE SCHEMA vault; CREATE TABLE cron.job(jobid bigint,jobname text,command text,active boolean); INSERT INTO cron.job VALUES(1,'invoke-email-worker','original',true),(2,'daily-storage-cleanup','storage',false); CREATE TABLE vault.secrets(name text); INSERT INTO vault.secrets VALUES('SUPABASE_SERVICE_ROLE_KEY'); CREATE FUNCTION cron.alter_job(job_id bigint,command text) RETURNS void LANGUAGE sql AS $$ UPDATE cron.job j SET command=$2 WHERE j.jobid=$1 $$;`);
await db.exec(readFileSync(root+'/supabase/migrations/20261008124439_authenticate_email_worker_cron.sql','utf8'));
const command=(await db.query("SELECT command FROM cron.job WHERE jobname='invoke-email-worker'")).rows[0].command;
assert.match(command,/vault\.decrypted_secrets/);
assert.match(command,/'Authorization'/);
assert.match(command,/timeout_milliseconds := 10000/);
assert.equal((await db.query("SELECT active FROM cron.job WHERE jobname='daily-storage-cleanup'")).rows[0].active,false);
await db.exec(readFileSync(root+'/maintenance/rollback/02-email-worker-cron.sql','utf8'));
const reverted=(await db.query("SELECT command FROM cron.job WHERE jobname='invoke-email-worker'")).rows[0].command;
assert.ok(!reverted.includes('Authorization'));
await db.exec(`INSERT INTO cron.job VALUES(3,'daily-booking-cleanup','booking',false),(4,'daily-email-log-cleanup','logs',false),(5,'auto-expire-bookings','expire',true); CREATE FUNCTION cron.alter_job(job_id bigint,active boolean) RETURNS void LANGUAGE sql AS $$ UPDATE cron.job j SET active=$2 WHERE j.jobid=$1 $$;`);
await db.exec(readFileSync(root+'/supabase/migrations/20261008124740_resume_existing_retention_jobs.sql','utf8'));
assert.equal((await db.query("SELECT count(*)::int AS n FROM cron.job WHERE jobname LIKE 'daily-%' AND active")).rows[0].n,3);
await db.exec(readFileSync(root+'/supabase/migrations/20261008125045_authenticate_storage_cleanup_cron.sql','utf8'));
const storage=(await db.query("SELECT command,active FROM cron.job WHERE jobname='daily-storage-cleanup'")).rows[0];
assert.equal(storage.active,true);
assert.match(storage.command,/vault\.decrypted_secrets/);
assert.match(storage.command,/'Authorization'/);
assert.match(storage.command,/timeout_milliseconds := 30000/);
assert.equal((await db.query("SELECT command,active FROM cron.job WHERE jobname='auto-expire-bookings'")).rows[0].command,'expire');
await db.exec(readFileSync(root+'/maintenance/rollback/04-storage-cleanup-cron.sql','utf8'));
const storageReverted=(await db.query("SELECT command,active FROM cron.job WHERE jobname='daily-storage-cleanup'")).rows[0];
assert.equal(storageReverted.active,true);
assert.ok(!storageReverted.command.includes('Authorization'));
const report={passed:13,checks:['email cron retrieves credential from Vault at runtime','email cron sends required Authorization header','email HTTP timeout configured','email-only migration preserves other job state','email rollback restores original command','all three retention jobs resumed','storage job remains active after authentication change','storage credential retrieved at runtime','storage Authorization header present','storage HTTP timeout configured','expiry command unchanged','storage rollback preserves active state','storage rollback restores original command'],engine:'PGlite PostgreSQL; isolated fixtures only',completed_at:new Date().toISOString()};
console.log(JSON.stringify(report));
await db.close();
