import {fileURLToPath} from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const root = fileURLToPath(new URL("../../", import.meta.url));
const db = new PGlite();
const ids = { client:'00000000-0000-4000-8000-000000000001', partner:'00000000-0000-4000-8000-000000000002', admin:'00000000-0000-4000-8000-000000000003' };
await db.exec(`
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA auth;
CREATE SCHEMA cron;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
CREATE TYPE public.user_role AS ENUM ('client','partner','admin');
CREATE TABLE public.profiles(id uuid PRIMARY KEY,role public.user_role DEFAULT 'client',name text,email text,phone text);
INSERT INTO public.profiles(id,role,name) VALUES ('${ids.client}','client','Client'),('${ids.partner}','partner','Partner'),('${ids.admin}','admin','Admin');
CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND role='admin') $$;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_select ON public.profiles FOR SELECT USING(auth.uid()=id);
CREATE POLICY own_update ON public.profiles FOR UPDATE USING(auth.uid()=id);
CREATE POLICY own_insert ON public.profiles FOR INSERT WITH CHECK(auth.uid()=id);
CREATE POLICY admin_select ON public.profiles FOR SELECT TO authenticated USING(public.is_admin());
CREATE TABLE public.transactions(id int PRIMARY KEY,amount numeric);
CREATE TABLE public.marketing_queue(id int PRIMARY KEY,content text);
CREATE TABLE public.contact_messages(id int PRIMARY KEY,message text);
CREATE TABLE public.marketing_settings(id int PRIMARY KEY,budget numeric);
INSERT INTO public.transactions VALUES(1,100);
INSERT INTO public.marketing_queue VALUES(1,'Existing');
INSERT INTO public.contact_messages VALUES(1,'Existing');
INSERT INTO public.marketing_settings VALUES(1,10);
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can send a message" ON public.contact_messages FOR INSERT WITH CHECK(true);
CREATE POLICY "Authenticated users can read contact messages" ON public.contact_messages FOR SELECT TO authenticated USING(true);
CREATE POLICY "Authenticated users can delete contact messages" ON public.contact_messages FOR DELETE TO authenticated USING(true);
ALTER TABLE public.marketing_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY marketing_settings_select ON public.marketing_settings FOR SELECT TO authenticated USING(true);
CREATE POLICY marketing_settings_update ON public.marketing_settings FOR UPDATE TO authenticated USING(true) WITH CHECK(true);
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon,authenticated,service_role;
CREATE TABLE cron.job(jobid bigint PRIMARY KEY,jobname text,active boolean);
INSERT INTO cron.job VALUES(1,'daily-booking-cleanup',true),(2,'daily-storage-cleanup',true),(3,'daily-email-log-cleanup',true),(4,'auto-expire-bookings',true);
CREATE FUNCTION cron.alter_job(job_id bigint,active boolean) RETURNS void LANGUAGE sql AS $$ UPDATE cron.job j SET active=$2 WHERE j.jobid=$1 $$;
CREATE FUNCTION public.cleanup_old_bookings() RETURNS void LANGUAGE sql AS $$ SELECT $$;
CREATE FUNCTION public.cleanup_old_email_logs() RETURNS void LANGUAGE sql AS $$ SELECT $$;
GRANT EXECUTE ON FUNCTION public.cleanup_old_bookings(), public.cleanup_old_email_logs() TO anon,authenticated,service_role;
`);
await db.exec(readFileSync(root+'/supabase/migrations/20261008124352_protect_profile_role_and_admin_data.sql','utf8'));
const passed=[];
async function context(role,user='') { await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}'; SET ROLE ${role};`); }
async function one(sql) { return (await db.query(sql)).rows[0]; }
function check(name,actual,expected) { assert.deepEqual(actual,expected,name); passed.push(name); }
await context('authenticated',ids.client);
await db.exec("UPDATE profiles SET role='admin',phone='123' WHERE id=auth.uid()");
check('client cannot change stored role; ordinary profile edits work',await one('SELECT role,phone FROM profiles WHERE id=auth.uid()'),{role:'client',phone:'123'});
check('role edit does not grant admin privileges',(await one('SELECT is_admin() AS allowed')).allowed,false);
await db.exec(`INSERT INTO profiles(id,name) VALUES('${ids.client}','Updated client') ON CONFLICT(id) DO UPDATE SET role=excluded.role,name=excluded.name`);
check('client upsert remains compatible',(await one('SELECT name FROM profiles WHERE id=auth.uid()')).name,'Updated client');
for (const table of ['transactions','marketing_queue','contact_messages','marketing_settings']) check('client cannot read '+table,(await one('SELECT count(*)::int AS n FROM '+table)).n,0);
check('client cannot update marketing settings',(await db.query('UPDATE marketing_settings SET budget=999 RETURNING id')).rows.length,0);
check('client cannot delete contact submissions',(await db.query('DELETE FROM contact_messages RETURNING id')).rows.length,0);
let rejected=false;
try { await db.exec(`INSERT INTO profiles(id,role) VALUES('${ids.client.slice(0,-1)}9','admin')`); } catch(e) { rejected=e.code==='42501'; }
check('client cannot insert a privileged profile',rejected,true);
check('client cannot invoke booking cleanup',(await one("SELECT has_function_privilege(current_user,'public.cleanup_old_bookings()','EXECUTE') AS allowed")).allowed,false);
await context('authenticated',ids.partner);
await db.exec(`INSERT INTO profiles(id,name) VALUES('${ids.partner}','Updated partner') ON CONFLICT(id) DO UPDATE SET role=excluded.role,name=excluded.name`);
check('partner upsert with default role preserves partner role',await one('SELECT role,name FROM profiles WHERE id=auth.uid()'),{role:'partner',name:'Updated partner'});
await db.exec(`INSERT INTO profiles(id,role,name) VALUES('${ids.partner}','admin','Partner again') ON CONFLICT(id) DO UPDATE SET role=excluded.role,name=excluded.name`);
check('partner cannot promote itself through upsert',(await one('SELECT role FROM profiles WHERE id=auth.uid()')).role,'partner');
await context('anon');
await db.exec("INSERT INTO contact_messages VALUES(2,'Public contact form')");
check('public contact form remains functional',true,true);
check('anonymous users cannot read transactions',(await one('SELECT count(*)::int AS n FROM transactions')).n,0);
await context('authenticated',ids.admin);
for (const table of ['transactions','marketing_queue','marketing_settings']) check('admin can read '+table,(await one('SELECT count(*)::int AS n FROM '+table)).n,1);
check('admin can read contact submissions',(await one('SELECT count(*)::int AS n FROM contact_messages')).n,2);
await db.exec('UPDATE marketing_settings SET budget=20 WHERE id=1; INSERT INTO marketing_queue VALUES(2,\'Admin draft\'); UPDATE transactions SET amount=110 WHERE id=1; DELETE FROM marketing_queue WHERE id=2;');
check('admin marketing and transaction writes remain functional',true,true);
await context('service_role');
await db.exec(`INSERT INTO profiles(id,role,name) VALUES('00000000-0000-4000-8000-000000000004','partner','Server-created partner')`);
check('trusted server can provision partner accounts',(await one("SELECT role FROM profiles WHERE id='00000000-0000-4000-8000-000000000004'")).role,'partner');
await db.exec(`UPDATE profiles SET role='client' WHERE id='00000000-0000-4000-8000-000000000004'`);
check('trusted server can manage roles',(await one("SELECT role FROM profiles WHERE id='00000000-0000-4000-8000-000000000004'")).role,'client');
await context('postgres');
check('destructive scheduled jobs are paused',(await one("SELECT count(*)::int AS n FROM cron.job WHERE active AND jobname LIKE 'daily-%'")).n,0);
check('reservation expiry schedule is preserved',(await one("SELECT active FROM cron.job WHERE jobname='auto-expire-bookings'")).active,true);
await db.exec(readFileSync(root+'/maintenance/rollback/01-profile-role-admin-data.sql','utf8'));
check('rollback restores original RLS configuration',(await one("SELECT relrowsecurity FROM pg_class WHERE oid='public.transactions'::regclass")).relrowsecurity,false);
check('rollback restores original cron configuration',(await one("SELECT count(*)::int AS n FROM cron.job WHERE active")).n,4);
await context('authenticated',ids.client);
check('rollback restores original contact policy',(await one('SELECT count(*)::int AS n FROM contact_messages')).n,2);
const result={passed:passed.length,checks:passed,engine:'PGlite PostgreSQL; isolated fixtures only',completed_at:new Date().toISOString()};
console.log(JSON.stringify(result));
await db.close();
